backend:
  name: github
  repo: slimbiz237/slim-biz-website
  branch: main
  base_url: https://slimbiz-oauth.infoslimbiz.workers.dev

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: blog
    label: Blog Posts
    folder: content/blog
    create: true
    delete: true
    format: json
    fields:
      - {name: title, label: Title, widget: string}
      - {name: date, label: Date, widget: string}
      - {name: category, label: Category, widget: string}
      - {name: tag, label: Tag, widget: string}
      - {name: readTime, label: Read Time, widget: string}
      - {name: excerpt, label: Excerpt, widget: text}
      - {name: body, label: Body, widget: markdown}
      - {name: author, label: Author, widget: string}
      - {name: img, label: Image URL, widget: string, required: false}
